#!/bin/bash

set -eu

git clone ${REPO_ROOT:?required} ${REPO_OUT:?required}

STEMCELL_OS=${STEMCELL_OS:-ubuntu-trusty}
STEMCELL_VERSION=$(cat stemcell/version)
STEMCELL_MAJOR_VERSION="${STEMCELL_VERSION%.*}"

releases=($(ls -d *-compiled-release))
for release in "${releases[@]}"; do

  tar -xzf $release/*.tgz $( tar -tzf $release/*.tgz | grep 'release.MF' )
  release_name=$( grep -E '^name: ' release.MF | awk '{print $2}' | tr -d "\"'" )
  release_version=$( grep -E '^version: ' release.MF | awk '{print $2}' | tr -d "\"'" )
  release_url=$(cat $release/url)
  release_sha1=$(sha1sum $release/*.tgz | awk '{print $1}')

  cat > ${REPO_OUT}/ops/9-$release_name-compiled-release.yml <<-YAML
- path: /releases/name=${release_name}?
  type: replace
  value:
    name:    "${release_name}"
    url:     "${release_url}"
    version: "${release_version}"
    sha1:    "${release_sha1}"
    stemcell:
      os: "${STEMCELL_OS}"
      version: "${STEMCELL_VERSION}"

YAML
done

if [[ -z $(git config --global user.email) ]]; then
  git config --global user.email "${GIT_EMAIL}"
fi
if [[ -z $(git config --global user.name) ]]; then
  git config --global user.name "${GIT_NAME}"
fi

pushd $REPO_OUT
  git merge --no-edit ${REPO_OUT_BRANCH}
  git add -A
  git status
  git commit -m "Bumped compiled releases/stemcell"
popd
